[project]
name = "st-tldw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "litellm>=1.81.10",
    "streamlit>=1.54.0",
    "youtube-transcript-api>=1.2.4",
    "langchain>=0.3",
    "langchain-community>=0.3",
    "rank-bm25>=0.2",
    "faiss-cpu>=1.9",
    "sentence-transformers>=3.0",
    "langchain-huggingface>=0.1",
    "streamlit-float>=0.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
